version: '3.1'

services:
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: senai_api

volumes:
  dbdata: